const PRODUCTS = [
  { id: 1, nombre: "Crumble de Manzana", precio: 150, img: "img/crumble.jpg",
    ingredientes: ["Manzana", "Harina", "Azúcar", "Manteca"], descripcion: "Crumble casero con manzana y canela." },
  { id: 2, nombre: "Pasta Frola Individual", precio: 100, img: "img/pastafrola.jpg",
    ingredientes: ["Dulce de membrillo", "Harina", "Manteca"], descripcion: "Pasta frola individual lista para regalar." },
  { id: 3, nombre: "Paletas de Chocolate Personalizadas", precio: 120, img: "img/paletas.jpg",
    ingredientes: ["Chocolate", "Decoración comestible"], descripcion: "Paletas decoradas para eventos." },
  { id: 4, nombre: "Alfajor Tipo Espejito", precio: 80, img: "img/alfajoresespejito.jpg",
    ingredientes: ["Dulce", "Chocolate", "Harina"], descripcion: "Alfajor con espejo brillante." },
  { id: 5, nombre: "Alfajor de Maicena", precio: 80, img: "img/alfajoresdemaicena.jpg",
    ingredientes: ["Maicena", "Dulce de leche", "Manteca"], descripcion: "Clásico alfajor de maicena." },
  { id: 6, nombre: "Alfajor de Chocolate", precio: 85, img: "img/alfajoresdechocolate.jpg",
    ingredientes: ["Chocolate", "Dulce de leche"], descripcion: "Alfajor bañado en chocolate." },
  { id: 7, nombre: "Cupcakes Rellenos x12", precio: 1000, img: "img/cupakes.jpg",
    ingredientes: ["Harina", "Azúcar", "Huevos", "Relleno"], descripcion: "Caja x12 cupcakes rellenos." },
  { id: 8, nombre: "Masitas Secas 1/2 KG", precio: 450, img: "img/masitas.jpg",
    ingredientes: ["Harina", "Manteca", "Azúcar"], descripcion: "Media kilo de masitas secas." },
  { id: 9, nombre: "Masitas Secas 1 KG", precio: 850, img: "img/masitas.jpg",
    ingredientes: ["Harina", "Manteca", "Azúcar"], descripcion: "Kilo de masitas secas." },
  { id: 10, nombre: "Cookies Personalizadas x6", precio: 550, img: "img/cookies.jpg",
    ingredientes: ["Harina", "Azúcar", "Manteca"], descripcion: "Cookies decoradas por encargo." },
  { id: 11, nombre: "Brownie con Dulce de Leche 24cm", precio: 1700, img: "img/brownie.jpg",
    ingredientes: ["Chocolate", "Harina", "Dulce de leche"], descripcion: "Brownie grande con dulce." },
  { id: 12, nombre: "Torta Chajá 24cm", precio: 1900, img: "img/torta.jpg",
    ingredientes: ["Merengue", "Crema", "Fruta"], descripcion: "Torta típica uruguaya." },
  { id: 13, nombre: "Torta Personalizada 24cm", precio: 2500, img: "img/tortapersonalizada.jpg",
    ingredientes: ["Base a elección", "Decoración personalizada"], descripcion: "Torta hecha a medida." },
  { id: 14, nombre: "Torta Clásica 24cm", precio: 2200, img: "img/tortaclasica.jpg",
    ingredientes: ["Bizcochuelo", "Crema", "Decoración"], descripcion: "Torta clásica para celebraciones." }
];
